# Generated by Django 3.2.5 on 2021-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createBook',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('bookTitle', models.TextField(max_length=200)),
                ('bookName', models.CharField(max_length=50)),
                ('bookImage', models.ImageField(upload_to='book/')),
            ],
        ),
    ]
