# Generated by Django 3.2.5 on 2021-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbook',
            name='bookYearsTearm',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
