# Generated by Django 3.2.5 on 2021-07-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0006_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(upload_to='book'),
        ),
    ]
