# Generated by Django 3.2.5 on 2021-07-18 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0008_alter_book_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='craeted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
