# Generated by Django 3.2.5 on 2021-07-21 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booksApp', '0013_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookLike',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisherm', to=settings.AUTH_USER_MODEL),
        ),
    ]
